-- Define overrides when playing on Easy

-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 100
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 1
NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 1
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_PLAYER = 1
NDefines.NAI.AI_FORT_PER_DEV_RATIO = 100
