-- Define overrides when playing on Very Hard

-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.GREAT_POWER_FRENZY_QUICKSTART = 1
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 0
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_PLAYER = 0
NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 0
NDefines.NAI.FORT_MAINTENANCE_CHEAT = 0
NDefines.NAI.AI_FORT_PER_DEV_RATIO = 50
NDefines.NAI.PRESS_THEM_FURTHER = 1
